language: objective-c
before_script:
  - export LANG=en_US.UTF-8
before_install:
  - brew update
  - brew install cloc
script:
  - cloc .
  - xctool -project GeoJSON.xcodeproj -scheme GeoJSON -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project GeoJSON.xcodeproj -scheme GeoJSON -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
